// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ArchiveMobileVideos(arg1) {
  return window['go']['app']['App']['ArchiveMobileVideos'](arg1);
}

export function BatchExtractAudio(arg1) {
  return window['go']['app']['App']['BatchExtractAudio'](arg1);
}

export function BatchRemoveVideoIntro(arg1) {
  return window['go']['app']['App']['BatchRemoveVideoIntro'](arg1);
}

export function ClipAndReplaceVideo(arg1) {
  return window['go']['app']['App']['ClipAndReplaceVideo'](arg1);
}

export function ClipVideo(arg1) {
  return window['go']['app']['App']['ClipVideo'](arg1);
}

export function ExtractAudio(arg1) {
  return window['go']['app']['App']['ExtractAudio'](arg1);
}

export function ExtractFrames(arg1) {
  return window['go']['app']['App']['ExtractFrames'](arg1);
}

export function ExtractM3u8Links(arg1) {
  return window['go']['app']['App']['ExtractM3u8Links'](arg1);
}

export function ExtractVideoThumbnail(arg1) {
  return window['go']['app']['App']['ExtractVideoThumbnail'](arg1);
}

export function GetTempDir() {
  return window['go']['app']['App']['GetTempDir']();
}

export function GetVideoFilesInDir(arg1) {
  return window['go']['app']['App']['GetVideoFilesInDir'](arg1);
}

export function GetWindowState() {
  return window['go']['app']['App']['GetWindowState']();
}

export function InitSettingsDb() {
  return window['go']['app']['App']['InitSettingsDb']();
}

export function MoveFiles(arg1) {
  return window['go']['app']['App']['MoveFiles'](arg1);
}

export function MovieDownload(arg1) {
  return window['go']['app']['App']['MovieDownload'](arg1);
}

export function MovieMerge(arg1) {
  return window['go']['app']['App']['MovieMerge'](arg1);
}

export function OpenExplorer(arg1) {
  return window['go']['app']['App']['OpenExplorer'](arg1);
}

export function ReadAssetFile(arg1) {
  return window['go']['app']['App']['ReadAssetFile'](arg1);
}

export function RemoveVideoIntro(arg1) {
  return window['go']['app']['App']['RemoveVideoIntro'](arg1);
}

export function RotateVideo(arg1) {
  return window['go']['app']['App']['RotateVideo'](arg1);
}

export function SaveWindowState(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SaveWindowState'](arg1, arg2, arg3, arg4);
}

export function ScanVideoDir(arg1) {
  return window['go']['app']['App']['ScanVideoDir'](arg1);
}

export function ScanVideos(arg1) {
  return window['go']['app']['App']['ScanVideos'](arg1);
}

export function SelectDirectory() {
  return window['go']['app']['App']['SelectDirectory']();
}

export function SelectVideoFile() {
  return window['go']['app']['App']['SelectVideoFile']();
}

export function SendToFrontend(arg1) {
  return window['go']['app']['App']['SendToFrontend'](arg1);
}
