// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {myVideo} from '../models';

export function ArchiveMobileVideos(arg1:app.ArchiveMobileVideosReq):Promise<app.ArchiveMobileVideosRes>;

export function BatchExtractAudio(arg1:myVideo.BatchExtractAudioReq):Promise<myVideo.BatchExtractAudioRes>;

export function BatchRemoveVideoIntro(arg1:myVideo.BatchRemoveVideoIntroReq):Promise<myVideo.BatchRemoveVideoIntroRes>;

export function ClipAndReplaceVideo(arg1:myVideo.ClipAndReplaceReq):Promise<myVideo.ClipAndReplaceRes>;

export function ClipVideo(arg1:myVideo.ClipVideoReq):Promise<myVideo.ClipVideoRes>;

export function ExtractAudio(arg1:myVideo.ExtractAudioReq):Promise<myVideo.ExtractAudioRes>;

export function ExtractFrames(arg1:myVideo.ExtractFramesReq):Promise<myVideo.ExtractFramesRes>;

export function ExtractM3u8Links(arg1:app.ExtractM3u8LinksReq):Promise<app.ExtractM3u8LinksRes>;

export function ExtractVideoThumbnail(arg1:myVideo.ExtractVideoThumbnailReq):Promise<myVideo.ExtractVideoThumbnailRes>;

export function GetTempDir():Promise<string>;

export function GetVideoFilesInDir(arg1:string):Promise<Array<string>>;

export function GetWindowState():Promise<app.WindowState>;

export function InitSettingsDb():Promise<void>;

export function MoveFiles(arg1:app.MoveFilesReq):Promise<app.MoveFilesRes>;

export function MovieDownload(arg1:app.MovieDownloadReq):Promise<void>;

export function MovieMerge(arg1:app.MovieMergeReq):Promise<void>;

export function OpenExplorer(arg1:string):Promise<void>;

export function ReadAssetFile(arg1:string):Promise<string>;

export function RemoveVideoIntro(arg1:myVideo.RemoveVideoIntroReq):Promise<myVideo.RemoveVideoIntroRes>;

export function RotateVideo(arg1:myVideo.RotateVideoReq):Promise<myVideo.RotateVideoRes>;

export function SaveWindowState(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function ScanVideoDir(arg1:myVideo.ScanVideoDirReq):Promise<myVideo.ScanVideoDirRes>;

export function ScanVideos(arg1:myVideo.ScanVideosReq):Promise<myVideo.ScanVideosRes>;

export function SelectDirectory():Promise<string>;

export function SelectVideoFile():Promise<string>;

export function SendToFrontend(arg1:Array<number>):Promise<void>;
